### ISSUE TITLE
correction proposal for the PET calculation

### ISSUE THREAD

**Issue by eddes** [ladybug-tools/ladybug-comfort#4]
Hello,

Thank you for providing this wonderful tool. This time it's our turn to try and contribute to the effort.

We recently found out that the routine used for the calculation of the PET comfort index contains errors (wrong reference environment and insensitivity to the level of clothing due to an outdated vapour transfer model). The details can be found in the article on ResearchGate https://www.researchgate.net/publication/324168880_The_PET_comfort_index_Questioning_the_model or in "Building & Environment" on ScienceDirect https://www.sciencedirect.com/science/article/pii/S0360132318301896

A corrected version of the code is proposed on this branch:
https://github.com/eddes/ladybug/blob/fd381ef563a0772c6095c917dbe1f890b4d5b95c/VDI_PET_propre_sobre_comments.py

We are grateful to D. Spasic (https://github.com/stgeorges), whose original python of the PET helped us much to start with.

Best regards,
Edouard Walther & Quentin Goestchel

**Comment by chriswmackey** [comment]
I finally got around to addressing this and the new module is here:
https://github.com/ladybug-tools/ladybug-comfort/blob/master/ladybug_comfort/pet.py

I managed to replace the scipy dependency with a native Python rootfinding implementation and I think that I have also found a suitable reference that will allow us to input metabolic rates in met instead of needing to know the Watts on top of the basal metabolism, which is very difficult to estimate in my experience.

Thanks again, @eddes  and @stgeorges !
